<?php
$image_url = esc_url(wp_get_attachment_url($this->old_new_id['media'][58]));
$art       = esc_url(wp_get_attachment_url($this->old_new_id['media'][9]));
$parallax_image_1 = $this->old_new_id['media'][65];
$rest_1 = $this->old_new_id['media'][105];
$rest_2 = $this->old_new_id['media'][106];
$rest_3 = $this->old_new_id['media'][107];
$parallax_image_2 = $this->old_new_id['media'][66];
$contact_form = $this->old_new_id['contactforms'][1889];

$content = '[vc_row full_height="yes" box_padding="no-padding" theme_color="dark" overlay="transparent-bg-5" css=".vc_custom_1443221629190{background-image: url('. $image_url .'?id=3053) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column extra_css="vc-col-fullheight slider-content"][vc_raw_html]JTNDdWwlMjBpZCUzRCUyMmZhZGUlMjIlM0UlMEElM0NsaSUzRSUwQSUzQ2gxJTIwY2xhc3MlM0QlMjJ0ZXh0LXVwcGVyY2FzZSUyMiUzRUNvbWUlMjBpbiUyMCUyNiUyMFRhc3RlJTNDJTJGaDElM0UlMEElM0MlMkZsaSUzRSUwQSUzQ2xpJTNFJTBBJTNDaDElMjBjbGFzcyUzRCUyMnRleHQtdXBwZXJjYXNlJTIyJTNFSElHSCUyMENMQVNTJTIwUFJPRkVTU0lPTkFMJTIwU0VSVklDRSUzQyUyRmgxJTNFJTBBJTNDJTJGbGklM0UlMEElM0NsaSUzRSUwQSUzQ2gxJTIwY2xhc3MlM0QlMjJ0ZXh0LXVwcGVyY2FzZSUyMiUzRUZyb20lMjBhbiUyME91dHN0YW5kaW5nJTIwQ2hlZiUzQyUyRmgxJTNFJTBBJTNDJTJGbGklM0UlMEElM0MlMkZ1bCUzRSUwQSUzQ2klMjBjbGFzcyUzRCUyMmljb24taG9tZS1pY28lMjBpY29uLWxhcmclMjIlM0UlM0MlMkZpJTNFJTBBJTNDcCUyMGNsYXNzJTNEJTIybXQzMCUyMGZvbnQyJTIyJTNFVmlzdWFsJTIwQ29tcG9zZXIlMjBGdWxsJTIwSGVpZ2h0JTIwQkcuJTNDJTJGcCUzRQ==[/vc_raw_html][/vc_column][/vc_row][vc_row box_padding="padding-100" extra_css="welcome-block"][vc_column offset="vc_col-md-7"][vc_column_text]<img class="img-responsive" src="'. $art .'" alt="1" />[/vc_column_text][/vc_column][vc_column text_align="text-center" offset="vc_col-md-5"][vc_add_heading icon_type="iconmoon" icon="icon-intro" title="ASIAN SPICY FOOD" subtitle="Welcome to Majesty"][vc_column_text]<p>Majesty is a team work of Majesty Restaurant Cafe, we aim at promoting the foodstuff industry through the branches , we establish and through the new dishes. and integrate between different cultures.</p>
<a class="btn btn-gold black" href="'. $this->site_url .'about-us/">READ MORE</a>[/vc_column_text][/vc_column][/vc_row][vc_row box_padding="padding-100" theme_color="dark" overlay="transparent-bg-3" extra_css="discover" parallax="image" parallax_image="'. $parallax_image_1 .'"][vc_column text_align="text-center"][vc_column_text]
<h1>WE CREATE DELICOUS MEMORIES</h1>
<p class="text-uppercase">You can promote your creative parallax effects</p>
<a class="btn btn-gold white" href="'. $this->site_url .'shop/">DISCOVER MORE</a>[/vc_column_text][/vc_column][/vc_row][vc_row box_padding="padding-100"][vc_column width="1/3"][vc_overlay_box title="RELAXING AMBIENCE" image="'. $rest_1 .'"]Creating good mood[/vc_overlay_box][/vc_column][vc_column width="1/3"][vc_overlay_box title="SUNDAY" image="'. $rest_2 .'"]We Open[/vc_overlay_box][/vc_column][vc_column width="1/3"][vc_overlay_box title="SPICY FOODS" image="'. $rest_3 .'"]We Offer Spicy Food[/vc_overlay_box][/vc_column][/vc_row][vc_row box_padding="padding-100" theme_color="dark" overlay="bg-pattern" parallax="image" parallax_image="'. $parallax_image_2 .'"][vc_column][vc_add_heading icon_type="iconmoon" icon="icon-intro" title="RESERVATION" subtitle="Book your table"][contact-form-7 id="'. $contact_form .'"][/vc_column][/vc_row][vc_row box_padding="padding-t-100"][vc_column extra_css="nopadding"][vc_add_heading icon_type="iconmoon" icon="icon-intro" title="APPETIZERS" subtitle="MEALS"][vc_woo_carousel_by_category cats="lunch" per_page="6"][/vc_column][/vc_row][vc_row box_padding="padding-t-100"][vc_column extra_css="nopadding"][vc_add_heading icon_type="iconmoon" icon="icon-intro" title="TRIPLE DIPPER" subtitle="Choose &amp; Taste"][vc_woo_carousel_by_category cats="lunch" per_page="6"][/vc_column][/vc_row][vc_row box_padding="padding-t-100"][vc_column extra_css="nopadding"][vc_add_heading icon_type="iconmoon" icon="icon-intro" title="MEALS" subtitle="Choose &amp; Taste"][vc_woo_carousel_by_category cats="drinks" per_page="6"][/vc_column][/vc_row][vc_row box_padding="padding-100"][vc_column extra_css="nopadding"][vc_add_heading icon_type="iconmoon" icon="icon-intro" title="LATEST NEWS" subtitle="Stay up to Date"][vc_custom_blog_grid category="-1" num="3"][/vc_column][/vc_row]';
echo $content;