<?php
$content = '<p>[sama_row type="fixed-width" cssclass=""]<br>
[sama_column cssclass="col-md-12"][sama_title_num title="STYLE #01" num="01" tag="h3" cssclass="mt30"][/sama_column]<br>
[sama_column cssclass="col-md-3"]<br>
[sama_pricing_table title="STANDARD" style="dark-price" price="3.99" currency="$" subtitle="PER MONTH" features="1GB Storage,2 Clients,5 Active Projects,5 Colors,Free Goodies,24/7 Email support" btntitle="BUY NOW" btnurl="#" target="_self" cssclass=""]<br>
[/sama_column]<br>
[sama_column cssclass="col-md-3"]<br>
[sama_pricing_table title="BUSINESS" style="dark-price" price="9.99" currency="$" subtitle="PER MONTH" features="2GB Storage,5 Clients,10 Active Projects,10 Colors,Free Goodies,24/7 Email support" btntitle="BUY NOW" btnurl="#" target="_self" cssclass=""]<br>
[/sama_column]<br>
[sama_column cssclass="col-md-3"]<br>
[sama_pricing_table title="PROEFESSIONAL" style="theme-color" price="18.99" currency="$" subtitle="PER MONTH" features="5GB Storage, 10 Clients,20 Active Projects,20 Colors,Free Goodies,24/7 Email support" btntitle="Buy Now" btnurl="#" target="_self" cssclass=""][/sama_column][sama_column cssclass="col-md-3"]<br>
[sama_pricing_table title="ULTIMATE" style="dark-price" price="99.98" currency="$" subtitle="" features="Unlimited Storage, Unlimited Clients,UnlimitedProjects,UnlimitedColors,Free Goodies,24/7 Email support" btntitle="BUY NOW" btnurl="#" target="_self" cssclass=""]<br>
[/sama_column]<br>
[/sama_row][sama_divider cssclass="" style="divider-icon"][sama_row type="fixed-width" cssclass="pricing-off-marg"][sama_column cssclass="col-md-12"][sama_title_num title="STYLE #02" num="02" tag="h3" cssclass="mt30 clearfix"][sama_empty_space height="20"][/sama_column]<br>
[sama_column cssclass="col-md-4"][sama_pricing_table title="STANDARD" style="dark-price" price="3.99" currency="$" subtitle="PER MONTH" features="1GB Storage,2 Clients,5 Active Projects,5 Colors,Free Goodies,24/7 Email support" btntitle="Buy now" btnurl="http://localhost/majestydemo//rozana/" target="_self" cssclass="customprice"][/sama_column][sama_column cssclass="col-md-4"][sama_pricing_table title="PROEFESSIONAL" style="dark-price" price="18.99" currency="$" subtitle="PER MONTH" features="5GB Storage,10 Clients,20 Active Projects,20 Colors,Free Goodies,24/7 Email support" btntitle="Buy now" btnurl="http://localhost/majestydemo//rozana/" target="_self" cssclass=""][/sama_column][sama_column cssclass="col-md-4"][sama_pricing_table title="ULTIMATE" style="theme-color" price="99.98" currency="$" subtitle="" features="Unlimited Storage,Unlimited Clients,Unlimited Projects,Unlimited Colors,Free Goodies,24/7 Email support" btntitle="Buy now" btnurl="#" target="_self" cssclass=""][/sama_column][/sama_row][sama_divider cssclass="" style="divider-icon"][sama_row type="fixed-width" cssclass="pricing-off-marg"][sama_column cssclass="col-md-12"][sama_title_num title="STYLE #03" num="03" tag="h3" cssclass="mt30"][sama_empty_space height="20"][/sama_column][sama_column cssclass="col-md-4"][sama_pricing_table title="STANDARD" style="green-price" price="3.99" currency="$" subtitle="PER MONTH" features="1GB Storage,2 Clients,5 Active Projects,5 Colors,Free Goodies,24/7 Email support" btntitle="Buy now" btnurl="http://localhost/majestydemo//rozana/" target="_self" cssclass=""][/sama_column][sama_column cssclass="col-md-4"][sama_pricing_table title="PROEFESSIONAL" style="dark-price" price="18.99" currency="$" subtitle="PER MONTH" features="5GB Storage,10 Clients,20 Active Projects,20 Colors,Free Goodies,24/7 Email support" btntitle="Buy now" btnurl="http://localhost/majestydemo//rozana/" target="_self" cssclass=""][/sama_column][sama_column cssclass="col-md-4"][sama_pricing_table title="ULTIMATE" style="wet-asphelt-price" price="99.98" currency="$" subtitle="" features="Unlimited Storage,Unlimited Clients,Unlimited Projects,Unlimited Colors,Free Goodies,24/7 Email support" btntitle="Buy now" btnurl="#" target="_self" cssclass=""][/sama_column][/sama_row][sama_empty_space height="100"]</p>';

echo $content;