<?php
$map = $this->old_new_id['media'][88];
$map_url  = esc_url(wp_get_attachment_url($map));

$content = '<p>[sama_icon name="fa fa-flag" font="fontawesome" cssclass="larg-icon"] Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.[sama_divider cssclass="" style="divider-dashed color-divider"]</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.[sama_divider cssclass="" style="divider-solid"]</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.[sama_divider cssclass="" style="divider-solid divider-3"]</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.[sama_divider cssclass="" style="divider-dotted"]</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>[sama_divider cssclass="" style="divider-img-1"]</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
<p>[sama_divider cssclass="" style="divider-img-2"]</p>
<p>[sama_icon name="fa fa-flag" font="fontawesome"] Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>[sama_left cssclass=""]<br class="removebr">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<br class="removebr">[/sama_left]</p>
<p>[sama_right cssclass=""]<br class="removebr">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<br class="removebr">[/sama_right]</p>
<p>[sama_row type="fixed-width"]<br class="removebr">[sama_column cssclass="col-md-3"]<br class="removebr">Enter Your Content Here<br class="removebr">[/sama_column]<br class="removebr">[sama_column cssclass="col-md-3"]<br class="removebr">Enter Your Content Here<br class="removebr">[/sama_column]<br class="removebr">[sama_column cssclass="col-md-3"]<br class="removebr">Enter Your Content Here<br class="removebr">[/sama_column]<br class="removebr">[sama_column cssclass="col-md-3"]</p>
<p>Enter Your Content Here<br class="removebr"><br class="removebr">[/sama_column]<br class="removebr">[/sama_row]</p>
<p>[sama_clear]</p>
<h3>Alert</h3>
<p>[sama_alert type="alert-success" close="yes"]<br class="removebr"> <strong>Holy guacamole!</strong> Best check yo self.<br class="removebr">[/sama_alert]</p>
<p>[sama_alert type="alert-success" close="no"]<br class="removebr"><strong>Holy guacamole!</strong> Best check yo self.<br class="removebr">[/sama_alert]</p>
<p>[sama_badge title="L" cssclass=" " style="dropcap"]orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.</p>
<p>[sama_badge title="L" cssclass=" " style="dropcap2"]orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.</p>
<p>[sama_badge title="L" cssclass=" " style="dropcap3"]orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.</p>
<p>[sama_blockquote float="left" style="syyle1"]lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever[/sama_blockquote]</p>
<p>[sama_blockquote float="left" style="style2"]lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever[/sama_blockquote]</p>
<p>[sama_blockquote float="left" style="style4"]lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever[/sama_blockquote]</p>
<p>[sama_blockquote float="left" source="Mostafa" beforsource="By" style="style3"]lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever[/sama_blockquote]</p>
<p>[sama_label title="Mostafa" style="label-default"]Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore [sama_label title="Warning" style="label-warning"]&nbsp;et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>&nbsp;</p>
<h3>Well</h3>
<p>[sama_well size="well-lg"]<br class="removebr">Enter Your Content Here<br class="removebr">[/sama_well]</p>
<p>[sama_well size="well-sm"]<br class="removebr">Enter Your Content Here<br class="removebr">[/sama_well]</p>
<p>[sama_jumbotron]</p>
<h1>Hello, world!</h1>
<p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
<p><a class="btn btn-primary btn-lg" href="#">Learn more</a></p>
<p><br class="removebr">[/sama_jumbotron]</p>
<p>[sama_title_icon title="ART OF FOOD" subtitle="Welcome to Majesty" tag="h2" icon="" cssclass=""]</p>
<p>[sama_title_icon title="ART OF FOOD" subtitle="Welcome to Majesty" tag="h2" icon="fa fa-flag larg-icon" cssclass=""]</p>
<p>[sama_title_num title="MAJESTY DIVIDER SOLID" num="01" tag="h3"]</p>
<p>[sama_gmaps title="Majesty" latlang="45.088530, -64.367951" zoom="17" image="'.$map_url.'" cssclass=""]</p>';

echo $content;