<?php
$old_pages_second_menu = array(1588, 1582, 1519, 1523, 1579, 1504, 1585, 1604, 1632, 1513, 1562, 1535, 1572 );
$pages_second_menu = array();
foreach( $old_pages_second_menu as $page ) {
	$pages_second_menu[] = $this->old_new_id['pages'][$page];
}
$old_pages_display_small_header = array( 1595, 3536, 5249, 5214);
$pages_display_small_header = array();
foreach( $old_pages_display_small_header as $page ) {
	$pages_display_small_header[] = $this->old_new_id['pages'][$page];
}
$old_owlcarouselpages = array( 5249, 1566);
$owlcarouselpages = array();
foreach( $old_owlcarouselpages as $page ) {
	$owlcarouselpages[] = $this->old_new_id['pages'][$page];
}
$old_countdow_pages = array(3089, 3095, 3093);
$countdow_pages = array();
foreach( $old_countdow_pages as $page ) {
	$countdow_pages[] = $this->old_new_id['pages'][$page];
}

$footer_logo = esc_url(wp_get_attachment_url($this->old_new_id['media'][214])); 
$theme_option = array(
		'theme_layout'					=> 'default',
		'boxed_type'					=> 'boxedbgcolor',
		'boxed_bg_color'				=> '#2a2a2a',
		'display_loader'				=> true,
		'loader_style'					=> 'loader',
		'display_breadcrumb'			=> true,
		'menu_color'					=> 'light',
		'logo_position'					=> 'default',
		'pages_scroll_menu'				=> '',
		'blog_type'						=> 'blog-list-small-thumb', 
		'blog_with_sidebar'				=> true,
		'blog_archive_type'				=> 'blog-list-small-thumb',
		'archive_with_sidebar'			=> true,
		'blog_excerpt'					=> 16,
		'btn_more_as'					=> 'text',
		'blog_mas_thumb'				=> 'masonrythumb',
		'single_gallery_at_top'			=> true,
		'single_display_share_icon'		=> true,
		'single_share_facebook'			=> true,
		'single_share_twitter'			=> true,
		'single_share_pinterest'		=> false,
		'single_share_gplus'			=> true,
		'single_share_linkedin'			=> false,
		'blog_single_post_bg'			=> false,
		'blog_single_subtitle'			=> 'All About Majesty',
		'blog_cat_bg'					=> true,
		'blog_tag_bg'					=> true,
		'blog_author_bg'				=> true,
		'team_mem_subtitle'				=> 'Every Thing You Know About Majesty',
		'display_email_at_team_archive' => false,
		'team_cat_bg'					=> true,
		'team_single_post_bg'			=> true,
		'display_related_members'		=> true,
		'related_member_title'			=> 'OUR TEAM',
		'related_member_sub_title'		=> 'The Friendlist Professional Chef',
		'related_member_num'			=> 9,
		'related_member_order'			=> 'DESC',
		'related_member_orderby'		=> 'date',
		'related_member_display_email'	=> false,
		'related_member_bg'				=> 'background',
		'related_bg_parallax'			=> 'yes',
		'related_bg_trans'				=> 'transparent-bg-3',
		'shop_type'						=> 'fullwidth',
		'shop_sid_pos'					=> 'left',
		'products_per_page'				=> 12,
		'display_top_cart'				=> true,
		'shop_cat_bg'					=> true,
		'shop_tag_bg'					=> false,
		'shop_display_single_images'	=> 'owlcarousel',
		'shop_display_share_icon'		=> true,
		'shop_share_facebook'			=> true,
		'shop_share_twitter'			=> true,
		'shop_share_pinterest'			=> false,
		'shop_share_gplus'				=> true,
		'shop_share_linkedin'			=> false,
		'shop_single_product_bg'		=> true,
		'shop_single_subtitle'			=> 'Come & Taste',
		'shop_display_rate_in_list2'	=> true,
		'shop_display_excerpt_in_list2'	=> true,
		'shop_display_thumbnail_in_list2'	=> true,
		'shop_display_ordering_result_count' => true,
		'shop_display_categories'		=> false,
		'shop_txt_link'					=> 'All Menu',
		'footer_type'					=> 	'4col',
		'display_foot_bottom'			=> true,
		'bottom_content'				=> '<img  src="'. $footer_logo .'"  alt="logo"><p> 2015 ALL RIGHT RESERVED. DESIGNED BY <a target="_blank" href="https://themeforest.net/item/majesty-restaurant-woocommerce-wordpress-theme/13483561">Eye Themes</a></p>',
		'enable_theme_color_style'		=> false,
		'themecolorstyle'				=> '',
		'enable_advanced_custom_color'	=> false,
		'majesty_main_color'			=> '#c59d5f',
		'majesty_body_color'			=> '#515151',
		'majesty_head_color'			=> '#262626',
		'majesty_icon_color'			=> '#e8e8e8',
		'majesty_calendar_color'		=> '#fcf8e3',
		'enable_typography'				=> false,
		'enable_custom_fonts'			=> false,
		'enable-font-opensans'			=> false,
		'font-opensans'					=> '',
		'font-opensans-style'			=> '',
		'font-opensans-subsets'			=> '',
		'enable-font-fjallaone'			=> false,
		'font-fjallaone'				=> '',
		'font-fjallaone-style'			=> '',
		'font-fjallaone-subsets'		=> '',
		'enable-font-courgette'			=> false,
		'font-courgette'				=> '',
		'font-courgette-style'			=> '',
		'font-courgette-subsets'		=> '',
		'enable_custom_css'				=> false,
		'enable_custom_js'				=> false,
		'countdow-pages'				=> '',
		'prettyphoto-pages'				=> '',
		'contactform7-pages'			=> '',
		'enable_small_hedaer'			=> false,
		'phone_number'					=> 'Hot Line +022 0100 843',
		'header_more_links'				=> '',
		'head_facebook'					=> 'https://www.facebook.com/',
		'head_twitter'					=> 'https://twitter.com/',
		'head_gplus'					=> 'https://plus.google.com/',
		'head_vimeo'					=> '',
		'head_youtube'					=> '',
		'head_instagram'				=> 'https://www.instagram.com/',
		'head_pinterest'				=> '',
		'head_tripadvisor'				=> 'http://www.tripadvisor.com/',
		'head_foursquare'				=> 'https://foursquare.com/',
		'small_hedaer_social_target'	=> '_self',
		'display_search_icon'			=> true,
		'boxed_bg_img'					=> '',
		'loader_logo'					=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][219])),
											'id'			=> $this->old_new_id['media'][219],
											'height'		=> '162',
											'width'			=> '244',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][219])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'logo-light-trans'			=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][218])),
											'id'			=> $this->old_new_id['media'][218],
											'height'		=> '54',
											'width'			=> '204',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][218])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'logo-light-small'			=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][216])),
											'id'			=> $this->old_new_id['media'][216],
											'height'		=> '40',
											'width'			=> '151',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][216])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'logo-white-bg'			=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][217])),
											'id'			=> $this->old_new_id['media'][217],
											'height'		=> '40',
											'width'			=> '151',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][217])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'logo-dark-small'			=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][215])),
											'id'			=> $this->old_new_id['media'][215],
											'height'		=> '40',
											'width'			=> '151',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][215])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'vertical-logo'			=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][220])),
											'id'			=> $this->old_new_id['media'][220],
											'height'		=> '166',
											'width'			=> '184',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][220])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'blog_single_bg'	=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][20])),
											'id'			=> $this->old_new_id['media'][20],
											'height'		=> '800',
											'width'			=> '1920',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][20])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'team_mem_head_bg'	=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][180])),
											'id'			=> $this->old_new_id['media'][180],
											'height'		=> '800',
											'width'			=> '1920',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][180])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'team_single_bg'	=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][180])),
											'id'			=> $this->old_new_id['media'][180],
											'height'		=> '800',
											'width'			=> '1920',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][180])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'related_bg_url'	=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][180])),
											'id'			=> $this->old_new_id['media'][180],
											'height'		=> '800',
											'width'			=> '1920',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][180])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'shop_single_bg'	=> array(
											'url'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][20])),
											'id'			=> $this->old_new_id['media'][20],
											'height'		=> '800',
											'width'			=> '1920',
											'thumbnail' 	=> esc_url(wp_get_attachment_url($this->old_new_id['media'][20])),
											'title'			=> '',
											'caption'		=> '',
											'alt'			=> '',
											'description'	=> '',							
		),
		'pages_second_menu'				=> $pages_second_menu,
		'pages_scroll_menu'				=> $pages_second_menu,
		'pages_display_small_header' 	=> $pages_display_small_header,
		'owl-carousel-pages'			=> $owlcarouselpages,
		'booking_page'					=> $this->old_new_id['pages'][2954],
		'countdow-pages'				=> $countdow_pages,		
		'menu_silder'					=> array(
											array(
												'url'			=> '#',
												'attachment_id'	=> $this->old_new_id['media'][203],
												'height'		=> '510',
												'width'			=> '564',
												'thumb' 		=> esc_url(wp_get_attachment_url($this->old_new_id['media'][203])),
												'image'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][203])),
												'title'			=> 'Staters',
												'description'	=> '',
												'sort'			=> 0
											),
											array(
												'url'			=> '#',
												'attachment_id'	=> $this->old_new_id['media'][204],
												'height'		=> '510',
												'width'			=> '564',
												'thumb' 		=> esc_url(wp_get_attachment_url($this->old_new_id['media'][204])),
												'image'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][204])),
												'title'			=> 'Dishes',
												'description'	=> '',
												'sort'			=> 1
											),
											array(
												'url'			=> '#',
												'attachment_id'	=> $this->old_new_id['media'][205],
												'height'		=> '510',
												'width'			=> '564',
												'thumb' 		=> esc_url(wp_get_attachment_url($this->old_new_id['media'][205])),
												'image'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][205])),
												'title'			=> 'Fishes',
												'description'	=> '',
												'sort'			=> 2
											),
											array(
												'url'			=> '#',
												'attachment_id'	=> $this->old_new_id['media'][206],
												'height'		=> '510',
												'width'			=> '564',
												'thumb' 		=> esc_url(wp_get_attachment_url($this->old_new_id['media'][206])),
												'image'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][206])),
												'title'			=> 'Salads',
												'description'	=> '',
												'sort'			=> 3
											),
											array(
												'url'			=> '#',
												'attachment_id'	=> $this->old_new_id['media'][207],
												'height'		=> '510',
												'width'			=> '564',
												'thumb' 		=> esc_url(wp_get_attachment_url($this->old_new_id['media'][207])),
												'image'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][207])),
												'title'			=> 'Deserts',
												'description'	=> '',
												'sort'			=> 4
											),
											array(
												'url'			=> '#',
												'attachment_id'	=> $this->old_new_id['media'][208],
												'height'		=> '510',
												'width'			=> '564',
												'thumb' 		=> esc_url(wp_get_attachment_url($this->old_new_id['media'][208])),
												'image'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][208])),
												'title'			=> 'Drinks',
												'description'	=> '',
												'sort'			=> 5
											),
											array(
												'url'			=> '#',
												'attachment_id'	=> $this->old_new_id['media'][209],
												'height'		=> '510',
												'width'			=> '564',
												'thumb' 		=> esc_url(wp_get_attachment_url($this->old_new_id['media'][209])),
												'image'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][209])),
												'title'			=> 'Soups',
												'description'	=> '',
												'sort'			=> 6
											),
											array(
												'url'			=> '#',
												'attachment_id'	=> $this->old_new_id['media'][210],
												'height'		=> '510',
												'width'			=> '564',
												'thumb' 		=> esc_url(wp_get_attachment_url($this->old_new_id['media'][210])),
												'image'			=> esc_url(wp_get_attachment_url($this->old_new_id['media'][210])),
												'title'			=> 'Combo Meals',
												'description'	=> '',
												'sort'			=> 7
											)
		
		)
);

update_option( 'majesty', $theme_option);